apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-banking-auditoria-v2
  labels:
    app: core-banking-auditoria-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: core-banking-auditoria-v2
  template:
    metadata:
      labels:
        app: core-banking-auditoria-v2
    spec:
      containers:
        - name: core-banking-auditoria
          image: core-banking-auditoria:1.0.0
          imagePullPolicy: Never
          ports:
            - containerPort: 8090