apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-banking-contas
  namespace: bank
  labels:
    app: core-banking-contas
  annotations:
    argocd.argoproj.io/tracking-id: contas:apps/Deployment:/core-banking-contas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: core-banking-contas
  template:
    metadata:
      labels:
        app: core-banking-contas
    spec:
      containers:
        - name: core-banking-contas
          image: core-banking-contas:1.0.0
          imagePullPolicy: Never
          ports:
            - containerPort: 8080