mp.messaging.incoming.words-in.auto.offset.reset=earliest
mp.messaging.incoming.words-in.topic=words
mp.messaging.outgoing.words-out.topic=words

mp.messaging.outgoing.account-events.connector=smallrye-kafka
mp.messaging.outgoing.account-events.topic=account-events
mp.messaging.outgoing.account-events.value.serializer=org.apache.kafka.common.serialization.StringSerializer

mp.messaging.incoming.account-events.connector=smallrye-kafka
mp.messaging.incoming.account-events.topic=account-events
mp.messaging.incoming.account-events.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer

kafka.bootstrap.servers=localhost:9092


