# =====================================
# KAFKA - PRODUCER
# =====================================

mp.messaging.outgoing.account-events-out.connector=smallrye-kafka
mp.messaging.outgoing.account-events-out.topic=account-events
mp.messaging.outgoing.account-events-out.value.serializer=io.quarkus.kafka.client.serialization.ObjectMapperSerializer

quarkus.otel.exporter.otlp.enabled=false