# =====================================
# KAFKA - PRODUCER
# =====================================

mp.messaging.outgoing.account-events-out.connector=smallrye-kafka
mp.messaging.outgoing.account-events-out.topic=account-events
mp.messaging.outgoing.account-events-out.value.serializer=io.quarkus.kafka.client.serialization.ObjectMapperSerializer

quarkus.otel.exporter.otlp.enabled=false

quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5433/svc_contas
quarkus.datasource.username=admin
quarkus.datasource.password=root

quarkus.hibernate-orm.database.generation=update