quarkus.application.name=core-banking-iam
quarkus.http.port=8087

# Datasource
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=iam
quarkus.datasource.password=iam
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/iam_db

# Hibernate
quarkus.hibernate-orm.database.generation=none

# Flyway
quarkus.flyway.migrate-at-start=true

# JWT
mp.jwt.verify.issuer=core-banking-iam
mp.jwt.verify.publickey.location=publicKey.pem
smallrye.jwt.sign.key.location=privateKey.pem

# Security
quarkus.http.auth.permission.authenticated.paths=/*
quarkus.http.auth.permission.authenticated.policy=authenticated

