# ACCOUNT EVENTS
mp.messaging.outgoing.account-events.connector=smallrye-kafka
mp.messaging.outgoing.account-events.topic=ledger-events
mp.messaging.outgoing.account-events.value.serializer=org.apache.kafka.common.serialization.StringSerializer

# KAFKA
kafka.bootstrap.servers=localhost:9092

quarkus.http.port=8091
